#!/bin/sh

# defaults

if [ ! -e index.php ] && [ ! -e wp-includes/version.php ]; then
  # install wordpress, new installation
  echo >&2 "WordPress not found in $PWD - copying now..."

  tar -cf - -C /usr/src/wordpress . | tar -xf - -C /var/www/html

  # create config
  cd /var/www/html && wp-cli config create --dbname="${WORDPRESS_DB_NAME:-wordpress}" --dbuser="${WORDPRESS_DB_USER:-root}" --dbpass="${WORDPRESS_DB_PASSWORD}" --dbhost="${WORDPRESS_DB_HOST:-mysql}"
  cd /var/www/html && wp-cli db create
fi

exec php-fpm
